# Generated by Django 4.1.7 on 2023-04-03 03:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('minmum_wage', models.PositiveBigIntegerField()),
                ('maximum_wage', models.PositiveBigIntegerField()),
                ('no_of_vacancy', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('position_time', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=9)),
                ('work_location', models.CharField(choices=[('Remote Location', 'Remote Location'), ('Office Location', 'Office Location')], default='Office Location', max_length=15)),
                ('level', models.CharField(choices=[('Entry', 'Entry Level'), ('Intermediate', 'Intermediate Level'), ('Senior', 'Senior Level')], default='Entry', max_length=12)),
                ('education', models.CharField(max_length=255)),
                ('experince', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('prefered_age', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
