# Generated by Django 4.1.7 on 2023-04-05 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.FileField(upload_to='user/coverLetter')),
                ('resume', models.FileField(upload_to='user/resume')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='user/certificates')),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_applied', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
