# Generated by Django 4.1.7 on 2023-04-06 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='applied_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_seekers', to='core.job'),
            preserve_default=False,
        ),
    ]
