# Generated by Django 4.1.7 on 2023-03-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, max_length=15000),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tax_id',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='description',
            field=models.TextField(blank=True, max_length=15000),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='tax_id',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
