# Generated by Django 4.1.7 on 2023-03-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_companyprofile_tax_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='date_of_establishment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='pan',
            field=models.ImageField(blank=True, null=True, upload_to='user/company/pan'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='registeration_no',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Public', 'Public'), ('Non-Profit Distributing', 'Non-Profit Distributing')], max_length=30, null=True),
        ),
    ]
