# Generated by Django 4.1.7 on 2023-03-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_companyprofile_date_of_establishment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='citizenship',
            field=models.ImageField(blank=True, null=True, upload_to='user/jobseeker/identity'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='user/jobseeker/resume'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user/jobseeker/profile/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='user/jobseeker/resume'),
        ),
    ]
